### PR TITLE
Configure router with provided routes

### LINKED ISSUE #9: Bug: Routes are not configured before initial navigation
The `provideRouter(routes)` function configures the routes for the router, but the `resetConfig` function isn't called until after the `Router` constructor is called. The initial navigation is called in the constructor of the `Router`.

### PR DESCRIPTION
**Pull request by brandonroberts**
Closes #9

### CODE REVIEW

**Comment by brandonroberts** [comment]
cc: @vsavkin

**Comment by brandonroberts** [comment]
@robwormald will you review?

**Comment by robwormald** [comment]
LGTM 👍

**Comment by vsavkin** [comment]
@brandonroberts thanks!

**Pull request merged**
